version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DB: 0
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data-redis:/data
    networks:
      - webnet

networks:
  webnet:
