apiVersion: v1
kind: Service
metadata:
  name: hello-cirolini-service
spec:
  selector:
    app: cirolini-python-redis
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirolini-python-redis
spec:
  selector:
    matchLabels:
      app: cirolini-python-redis
  replicas: 4
  template:
    metadata:
      labels:
        app: cirolini-python-redis
    spec:
      containers:
      - name: cirolini-python-redis
        image: cirolini/cirolini-python-redis:2.0
        env:
        - name: REDIS_HOST
          value: "redis.default.svc"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        ports:
        - containerPort: 5000
